### ISSUE TITLE
I am facing a error

### ISSUE THREAD

**Issue by soumyadebna** [tpmmthomas/binance-copy-trade-bot#25]
I tried everything but I am facing this error

(trading) soumyadebnath16@Soumyas-MacBook-Air Bybit % python -m app.tgb_main
Traceback (most recent call last):
  File "/Users/soumyadebnath16/Developer/anaconda3/envs/trading/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/soumyadebnath16/Developer/anaconda3/envs/trading/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/soumyadebnath16/binance-copy-trade-bot/Bybit/app/tgb_main.py", line 2, in <module>
    from app.telegram_frontend.tgb_db import dbOperations
  File "/Users/soumyadebnath16/binance-copy-trade-bot/Bybit/app/telegram_frontend/tgb_db.py", line 5, in <module>
    from pybit.usdt_perpetual import HTTP
ModuleNotFoundError: No module named 'pybit.usdt_perpetual'
(trading) soumyadebnath16@Soumyas-MacBook-Air Bybit %

**Comment by tpmmthomas** [comment]
The bot is now rebranded to TraderCloneX, and is available as a service so that you do not need to run the server on your own!!! You could make use our hosted telegram server and make trades directly without worrying about technical details. Please make a registration here: https://forms.gle/98SpxWP7BgjCbxe47. We will provide you with detailed instructions on how to onboard the service soon. Ask any questions in the discussion tab.
