### ISSUE TITLE
code problem with mongodb

### ISSUE THREAD

**Issue by mistermoh223** [tpmmthomas/binance-copy-trade-bot#28]
hi bro
I have an error while doing the step 4 Run python -m  app.ct_main
I dont know how to Fill in the required fields in app/data/credentials.py such as 
auth_code = ""  # set it yourself                   **where do i have the authentification code?**
admin_code = ""  # set it yourself                     **where do i have the admin code?**
ip = ""                                                                **where do i have the ip?**

C:\Users\SIDIBE\Desktop\BOT\binance-copy-trade-bot>python -m  app.ct_main
2024-03-02 16:54:04,164 - app.copy_trade_backend.ct_globals - INFO - mongodb://Admin:123456@localhost:27017/
db path is mongodb://Admin:123456@localhost:27017/
2024-03-02 16:54:04,183 - __main__ - INFO - The copy trade program has started running.
Exception in thread pymongo_server_monitor_thread:
Traceback (most recent call last):
  File "C:\Users\SIDIBE\miniconda3\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\SIDIBE\miniconda3\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\periodic_executor.py", line 133, in _run
    if not self._target():
           ^^^^^^^^^^^^^^
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\monitor.py", line 61, in target
    monitor._run()  # type:ignore[attr-defined]
    ^^^^^^^^^^^^^^
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\monitor.py", line 213, in _run
    self._start_rtt_monitor()
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\monitor.py", line 167, in _start_rtt_monitor
    self._rtt_monitor.open()
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\monitor.py", line 87, in open
    self._executor.open()
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\periodic_executor.py", line 95, in open
    thread.start()
  File "C:\Users\SIDIBE\miniconda3\Lib\threading.py", line 992, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\SIDIBE\miniconda3\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\SIDIBE\Desktop\BOT\binance-copy-trade-bot\app\copy_trade_backend\ct_position.py", line 521, in run
    urls = self.userdb.retrieve_traders()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SIDIBE\Desktop\BOT\binance-copy-trade-bot\app\copy_trade_backend\ct_db.py", line 101, in retrieve_traders
    for x in self.tradertable.find():
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\cursor.py", line 1264, in next
    if len(self.__data) or self._refresh():
                           ^^^^^^^^^^^^^^^
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\cursor.py", line 1181, in _refresh
    self.__send_message(q)
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\cursor.py", line 1060, in __send_message
    response = client._run_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\_csot.py", line 107, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\mongo_client.py", line 1394, in _run_operation
    return self._retryable_read(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\mongo_client.py", line 1492, in _retryable_read
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\_csot.py", line 107, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\mongo_client.py", line 1462, in _retry_internal
    ).run()
      ^^^^^
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\mongo_client.py", line 2315, in run
    return self._read() if self._is_read else self._write()
           ^^^^^^^^^^^^
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\mongo_client.py", line 2437, in _read
    self._server = self._get_server()
                   ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\mongo_client.py", line 2400, in _get_server
    return self._client._select_server(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\mongo_client.py", line 1292, in _select_server
    topology = self._get_topology()
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\mongo_client.py", line 1238, in _get_topology
    self._topology.open()
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\topology.py", line 201, in open
    self._ensure_opened()
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\topology.py", line 652, in _ensure_opened
    server.open()
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\server.py", line 70, in open
    self._monitor.open()
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\monitor.py", line 87, in open
    self._executor.open()
  File "C:\Users\SIDIBE\miniconda3\Lib\site-packages\pymongo\periodic_executor.py", line 95, in open
    thread.start()
  File "C:\Users\SIDIBE\miniconda3\Lib\threading.py", line 992, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown

thank you

**Comment by tpmmthomas** [comment]
You have to set it yourself - meaning that you decide on those values yourself to protect your own bot.

IP is the ip address of the machine you are running the program on.

**Comment by mistermoh223** [comment]
![image](https://github.com/tpmmthomas/binance-copy-trade-bot/assets/147990352/1cc782b1-2ea7-45ff-8ff1-ac8abaffc55d)
 I STILL have this as an error message
